version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps): update dependencies'
      include: scope
    target-branch: main
